### ISSUE TITLE
preserve white space for stacktraces

### ISSUE THREAD

**Issue by janat08** [mixu/minilog#42]
stacktraces are aweful.

**Comment by janat08** [comment]
```
backend debug {"data":{"login":{"tokens":{"accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYXNkZiIsInVzZXJuYW1lIjoiYXNkZiIsInJvbGUiOiJhc2RmIiwiZnVsbE5hbWUiOm51bGx9LCJpYXQiOjE1MzcyMTMwNTMsImV4cCI6MTUzNzIxMzExM30.M-t5rY8nA4RhQeNOzjiWxHbE4qO8w84MIt61Df7Urqs","refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYXNkZiIsImlhdCI6MTUzNzIxMzA1MywiZXhwIjoxNTM3ODE3ODUzfQ.xpemrOGnjq287wZQ--benhCcpAqrKUH4LgE8tsYW67s","__typename":"Tokens"},"user":null,"errors":null,"__typename":"AuthPayload"}},"errors":[{"message":"Int cannot represent non 32-bit signed integer value: asdf","locations":[{"line":9,"column":3}],"path":["login","user","id"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["TypeError: Int cannot represent non 32-bit signed integer value: asdf","
   at coerceInt (C:\\Users\\user\\dev\\react-head\\node_modules\\graphql\\type\\scalars.js:36:11)","    at GraphQLScalarType.serialize (C:\\Users\\user\\dev\\react-head\\node_modules\\graphql\\type\\definition.js:418:12)","    at completeLeafValue (C:\\Users\\user\\dev\\react-head\\node_modules\\graphql\\execution\\execute.js:701:37)","    at completeValue (C:\\Users\\user\\dev\\react-head\\node_modules\\graphql\\execution\\execute.js:649:12)","    at completeValue (C:\\Users\\user\\dev\\react-head\\node_modules\\graphql\\execution\\execute.js:629:21)","    at completeValueWithLocatedError (C:\\Users\\user\\dev\\react-head\\node_modules\\graphql\\execution\\execute.js:580:21)","    at completeValueCatchingError (C:\\Users\\user\\dev\\react-head\\node_modules\\graphql\\execution\\execute.js:550:12)","
at resolveField (C:\\Users\\user\\dev\\react-head\\node_modules\\graphql\\execution\\execute.js:497:10)","    at C:\\Users\\user\\dev\\react-head\\node_modules\\graphql\\execution\\execute.js:364:18","    at Array.reduce (<anonymous>)"]}}}]} <= login({"input":{"usernameOrEmail":"asdf","password":"asdf"}})
2018-09-17T19:37:33.776Z INFO  [INCOMING] ::1 - POST /graphql HTTP/1.1 200 - - 435.965 ms
```
